mysql: &mysql
  adapter: mysql2
  host: localhost
  port: 3306
  username: root
  password: karimbenzema
#  socket: /tmp/mysql.sock
  charset: utf8
  collation: utf8_bin

postgres: &postgres
  adapter: postgresql
  host: localhost
  port: 5432
  username: root
  password: karimbenzema
  encoding: unicode

# Comment the the mysql line and uncomment the postgres line
# if you want to use postgres
choose: &choose
  # Choose one of the following
  <<: *mysql
  #<<: *postgres
  
##################################################
#### CONFIGURE ABOVE #############################
##################################################

# Normally you don't need to touch anything here

postgres_travis: &postgres_travis
  adapter: postgresql
  username: root
common: &common
  <<: *choose
development:
  <<: *common
  database: Evergreen_development
production:
  <<: *common
  database: Evergreen_production
test:
  <<: *common
  database: "Evergreen_test"
integration1:
  <<: *common
  database: Evergreen_integration1
integration2:
  <<: *common
  database: Evergreen_integration2
